name: panvimdoc

on: [push]

jobs:
  docs:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    steps:
      - uses: actions/checkout@v5
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: input-runner.nvim # Output vimdoc project name (required)
          # The following are all optional
          pandoc: "README.md" # Input pandoc file
          toc: true # Table of contents
          treesitter: true # Use treesitter for highlighting codeblocks
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto generate docs"
          branch: ${{ github.head_ref }}
